-- timefrontiers/php-sms — fresh v1.1 installation
-- Replace/select the database before running this file. Application queries
-- use the validated db_name supplied to Sms::configure().

CREATE TABLE `sms` (
  `id`                     BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code`                   VARCHAR(15) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `status`                 ENUM('pending','dispatching','queued','sent','failed','unknown','delivered') NOT NULL DEFAULT 'pending',
  `provider`               VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `idempotency_scope`      VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `idempotency_key_hash`   BINARY(32) NOT NULL,
  `version`                INT UNSIGNED NOT NULL DEFAULT 0,
  `message_id`             BIGINT UNSIGNED NULL DEFAULT NULL,
  `direction`              ENUM('outbound','inbound') NOT NULL DEFAULT 'outbound',
  `user`                   VARCHAR(15) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'SYSTEM',
  `batch`                  VARCHAR(15) CHARACTER SET ascii COLLATE ascii_bin NULL DEFAULT NULL,
  `sender`                 VARCHAR(16) NOT NULL,
  `receiver`               VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `message`                TEXT NOT NULL,
  `_message_pages`         TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `message_encoding`       ENUM('GSM-7','UCS-2') NOT NULL DEFAULT 'GSM-7',
  `fees_currency`          VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL DEFAULT NULL,
  `fees`                   DECIMAL(18,8) NOT NULL DEFAULT 0.00000000,
  `reference`              VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL DEFAULT NULL,
  `meta`                   JSON NULL DEFAULT NULL,
  `last_error_code`        VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL DEFAULT NULL,
  `dispatch_started_at`    TIMESTAMP(6) NULL DEFAULT NULL,
  `provider_accepted_at`   TIMESTAMP(6) NULL DEFAULT NULL,
  `reconciled_at`          TIMESTAMP(6) NULL DEFAULT NULL,
  `content_expires_at`     TIMESTAMP NULL DEFAULT NULL,
  `content_redacted_at`    TIMESTAMP(6) NULL DEFAULT NULL,
  `_created`               TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `_updated`               TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sms_code` (`code`),
  UNIQUE KEY `uq_sms_idempotency` (`idempotency_scope`, `idempotency_key_hash`),
  UNIQUE KEY `uq_sms_provider_reference` (`provider`, `reference`),
  KEY `idx_sms_user` (`user`),
  KEY `idx_sms_batch` (`batch`),
  KEY `idx_sms_message_id` (`message_id`),
  KEY `idx_sms_recovery` (`status`, `dispatch_started_at`),
  KEY `idx_sms_content_expiry` (`content_expires_at`),
  CONSTRAINT `chk_sms_public_code` CHECK (`code` REGEXP '^828[0-9]{8,12}$'),
  CONSTRAINT `chk_sms_message_pages` CHECK (`_message_pages` BETWEEN 1 AND 20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sms_delivery_event` (
  `id`                     BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sms_id`                 BIGINT UNSIGNED NOT NULL,
  `provider`               VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `event_id`               VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL DEFAULT NULL,
  `event_fingerprint`      BINARY(32) NOT NULL,
  `status`                 VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `outcome`                ENUM('processing','updated','duplicate','ignored','invalid','infrastructure_failed') NOT NULL DEFAULT 'processing',
  `safe_meta`              JSON NULL DEFAULT NULL,
  `received_at`            TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `processed_at`           TIMESTAMP(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sms_delivery_event_fingerprint` (`provider`, `event_fingerprint`),
  UNIQUE KEY `uq_sms_delivery_event_id` (`provider`, `event_id`),
  KEY `idx_sms_delivery_event_sms` (`sms_id`, `received_at`),
  CONSTRAINT `fk_sms_delivery_event_sms` FOREIGN KEY (`sms_id`) REFERENCES `sms` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
